# Generated by Django 3.1.13 on 2021-10-15 04:23

from django.db import migrations


categories_names_list = [
    "Desarrollo de Software", 
    "Servicio al Cliente",  
    "Ventas",
    "Mercadeo",
    "Diseño de Experiencia de Usuario", 
    "Diseño Grafico", 
    "Devops",
    "Front End",
    "Full Stack",
    "Desarrollador Mobile",
    "Desarrollador Video Juegos",
    "Administradores de Sistemas",
    "Blockchain y Crypto",
    "Multimedia",
    "Back End", 
    "Legal", 
    "QA", 
    "No Tecnologico", 
    "Otros"
    ]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('jobposts', 'Category')
    for category_name in categories_names_list:
        Category.objects.create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
    
