# Generated by Django 3.1.13 on 2021-10-17 02:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0003_auto_20211016_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='how_to_apply',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
