# Generated by Django 3.1.13 on 2021-10-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0004_auto_20211016_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
