# Generated by Django 3.1.13 on 2021-10-17 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0005_auto_20211016_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='descripción'),
        ),
    ]
