# Generated by Django 3.1.13 on 2021-10-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0006_auto_20211016_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lindkedin_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter_url',
        ),
    ]
