# Generated by Django 3.1.13 on 2021-10-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0009_auto_20211024_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('Menos de 10', 'Micro'), ('10-50 Empleados', 'Small'), ('50-500 Empleados', 'Medium'), ('500-2000 Empleados', 'Large'), ('+2000 Empleados', 'X Large')], default='Menos de 10', max_length=20, verbose_name='Tamaño de la compañía'),
        ),
    ]
