# Generated by Django 3.1.13 on 2021-11-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0011_auto_20211103_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='view_count',
        ),
    ]
