# Generated by Django 3.1.13 on 2022-04-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0013_auto_20211108_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='source',
            field=models.CharField(default='User Generated', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(default='User Generated', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
