# Generated by Django 3.1.13 on 2022-04-06 20:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0014_auto_20220406_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
