# Generated by Django 4.0.3 on 2022-04-20 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0015_auto_20220406_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
