# Generated by Django 3.1.13 on 2021-10-15 04:23

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('jobposts', 'Category')
    for category in Category.objects.all():
        category.source = "User Generated"
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0016_alter_jobpost_created'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
    
