# Generated by Django 4.0.3 on 2022-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0017_insert_category_default_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.CharField(default='User Generated', max_length=255),
        ),
    ]
