# Generated by Django 4.0.3 on 2022-05-23 15:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0018_category_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'created'], unique=True, verbose_name='slug'),
        ),
    ]
