# Generated by Django 3.1.13 on 2021-10-15 04:23

from django.db import migrations

def create_newsletter(apps, schema_editor):
    Newsletter = apps.get_model('newsletter', 'Newsletter')
    Site = apps.get_model('sites', 'Site')
    
    newsletter = Newsletter.objects.create(
        title="Trabaja Remoto Newsletter",
        email="leonardo@codetiger.co",
        slug="feline",
        sender="Leonardo Jimenez"
    )

    newsletter.site.set([Site.objects.get_current()])
    newsletter.save()
    
class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
        ('newsletter', '0005_auto_20190918_0122'),
        ('sites', '0004_alter_options_ordering_domain')
    ]

    operations = [
        migrations.RunPython(create_newsletter),
    ]
    